fun main(args: Array<String>){
    val data = 20 / 0   //may throw exception
    println("code below exception ...")

}

/*
This above program generates an exception, which causes rest of code below the exception not executable.
*/